
import localFont from "next/font/local";
import "./globals.css";
import dynamic from 'next/dynamic';
const Sidebar = dynamic(() => import('./Sidebar'), { ssr: false });
// import {ConfigProvider} from "antd";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Head from "next/head";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Head>
        <link href='https://fonts.googleapis.com/css?family=DM Sans' rel='stylesheet'/>
        </Head>
        <AntdRegistry theme={{
          backgroundColor:"blue"
        }}>
        <Sidebar children={children}/>
        <div>
        {children}
        </div>
        </AntdRegistry> 
      </body>
    </html>
  );
}
